// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package observe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type observeCsFlowStats struct {
	IngressPackets uint64
	IngressBytes   uint64
	EgressPackets  uint64
	EgressBytes    uint64
	FirstSeenNs    uint64
	LastSeenNs     uint64
	Family         uint16
	SrcPort        uint16
	DstPort        uint16
	Pad            uint16
	SrcIp          [16]uint8
	DstIp          [16]uint8
}

// loadObserve returns the embedded CollectionSpec for observe.
func loadObserve() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ObserveBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load observe: %w", err)
	}

	return spec, err
}

// loadObserveObjects loads observe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*observeObjects
//	*observePrograms
//	*observeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadObserveObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadObserve()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// observeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type observeSpecs struct {
	observeProgramSpecs
	observeMapSpecs
	observeVariableSpecs
}

// observeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type observeProgramSpecs struct {
	ObserveEgress  *ebpf.ProgramSpec `ebpf:"observe_egress"`
	ObserveIngress *ebpf.ProgramSpec `ebpf:"observe_ingress"`
	ObserveRelease *ebpf.ProgramSpec `ebpf:"observe_release"`
}

// observeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type observeMapSpecs struct {
	ObserveStats *ebpf.MapSpec `ebpf:"observe_stats"`
}

// observeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type observeVariableSpecs struct {
}

// observeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadObserveObjects or ebpf.CollectionSpec.LoadAndAssign.
type observeObjects struct {
	observePrograms
	observeMaps
	observeVariables
}

func (o *observeObjects) Close() error {
	return _ObserveClose(
		&o.observePrograms,
		&o.observeMaps,
	)
}

// observeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadObserveObjects or ebpf.CollectionSpec.LoadAndAssign.
type observeMaps struct {
	ObserveStats *ebpf.Map `ebpf:"observe_stats"`
}

func (m *observeMaps) Close() error {
	return _ObserveClose(
		m.ObserveStats,
	)
}

// observeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadObserveObjects or ebpf.CollectionSpec.LoadAndAssign.
type observeVariables struct {
}

// observePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadObserveObjects or ebpf.CollectionSpec.LoadAndAssign.
type observePrograms struct {
	ObserveEgress  *ebpf.Program `ebpf:"observe_egress"`
	ObserveIngress *ebpf.Program `ebpf:"observe_ingress"`
	ObserveRelease *ebpf.Program `ebpf:"observe_release"`
}

func (p *observePrograms) Close() error {
	return _ObserveClose(
		p.ObserveEgress,
		p.ObserveIngress,
		p.ObserveRelease,
	)
}

func _ObserveClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed observe_bpfel.o
var _ObserveBytes []byte
