// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package enforce

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type enforceVerdictVal struct {
	Action       uint32
	Pad          uint32
	DroppedPkts  uint64
	DroppedBytes uint64
	Tokens       uint64
	LastNs       uint64
	Rate         uint64
	Burst        uint64
}

// loadEnforce returns the embedded CollectionSpec for enforce.
func loadEnforce() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_EnforceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load enforce: %w", err)
	}

	return spec, err
}

// loadEnforceObjects loads enforce and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*enforceObjects
//	*enforcePrograms
//	*enforceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadEnforceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadEnforce()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// enforceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type enforceSpecs struct {
	enforceProgramSpecs
	enforceMapSpecs
	enforceVariableSpecs
}

// enforceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type enforceProgramSpecs struct {
	EnforceEgress  *ebpf.ProgramSpec `ebpf:"enforce_egress"`
	EnforceRelease *ebpf.ProgramSpec `ebpf:"enforce_release"`
}

// enforceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type enforceMapSpecs struct {
	VerdictMap *ebpf.MapSpec `ebpf:"verdict_map"`
}

// enforceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type enforceVariableSpecs struct {
}

// enforceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadEnforceObjects or ebpf.CollectionSpec.LoadAndAssign.
type enforceObjects struct {
	enforcePrograms
	enforceMaps
	enforceVariables
}

func (o *enforceObjects) Close() error {
	return _EnforceClose(
		&o.enforcePrograms,
		&o.enforceMaps,
	)
}

// enforceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadEnforceObjects or ebpf.CollectionSpec.LoadAndAssign.
type enforceMaps struct {
	VerdictMap *ebpf.Map `ebpf:"verdict_map"`
}

func (m *enforceMaps) Close() error {
	return _EnforceClose(
		m.VerdictMap,
	)
}

// enforceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadEnforceObjects or ebpf.CollectionSpec.LoadAndAssign.
type enforceVariables struct {
}

// enforcePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadEnforceObjects or ebpf.CollectionSpec.LoadAndAssign.
type enforcePrograms struct {
	EnforceEgress  *ebpf.Program `ebpf:"enforce_egress"`
	EnforceRelease *ebpf.Program `ebpf:"enforce_release"`
}

func (p *enforcePrograms) Close() error {
	return _EnforceClose(
		p.EnforceEgress,
		p.EnforceRelease,
	)
}

func _EnforceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed enforce_bpfel.o
var _EnforceBytes []byte
